CREATE TABLE students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(10),
    apaar_id VARCHAR(50),
    aadhaar_number VARCHAR(20),
    category VARCHAR(20),
    address TEXT,
    photo BOOLEAN DEFAULT FALSE,
    previous_school_tc BOOLEAN DEFAULT FALSE,
    admission_class VARCHAR(10),
    admission_date DATE,
    enrollment_no VARCHAR(50) UNIQUE,
    previous_marksheet BOOLEAN DEFAULT FALSE,
    blood_group VARCHAR(5),
    allergies_conditions TEXT,
    immunization BOOLEAN DEFAULT FALSE,
    height_cm INT,
    weight_kg INT,
    vision_check VARCHAR(20),
    character_cert VARCHAR(50),
    fee_status VARCHAR(50),
    attendance_percent DECIMAL(5,2),
    udise_uploaded BOOLEAN DEFAULT FALSE,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);